### ISSUE TITLE
关于LSDA与CEL设计的疑问

### ISSUE THREAD

**Issue by kpmokpmo** [cheerss/CrossFormer#1]
大神好，非常感谢你们的作品。有几个小疑问：

1. 貌似LDA和SDA是交替使用的，如果调整S和L的比例或顺序是否会对结果有影响。比如一个stage中SLS或SSLLL这样的。
2. 我看G貌似一直都是7，如果在金字塔结构中，将G逐步变为7,5,3,1(vanilla attention)，不知对效果影响如何
3. CEL放在最开始可以理解为提取多尺度信息。但随着层数的加深，可能H*W这个维度的空间位置意义越来越稀薄，那么再去提取多尺度信息可能很难用多尺度空间信息去解释了。不知后面不再加[2,4]的CEL是否有显著影响？
4. 抛开代码实现的整洁问题，kernel=32是不是太大了，换成kernel=3的堆叠应该不影响吧

非常感谢

**Comment by cheerss** [comment]
Thanks for your attention and questions first. The answers:

1. Our experiments indicate that decreasing the number of LDA may affect the performance. For example, we tried to use LDA only at the last layer of each stage (and use SDA for other layers), and the accuracy drops about 0.3%~0.4% (from 82.5 -> ~82.1%). The consequence of shuffling LDA and SDA is still unknown (e.g. from SLSLSL to SSSLLL), and using them alternately is just an intuitive choice.

2. It is also an interesting question but no answer yet.

3. The answer is: "CEL is important for all stages. We tried to delete CEL at stage-2/3/4, i.e., using single-scale kernel, and got a large performance drop (0.6%, from 82.5% to 81.9%).

4. You may wish to use 4x4 and 8x8 only at the first stage because the performance drop in this case is limited (about 0.1%~0.2%).

All results above are reported on ImageNet dataset with CrossFormer-S as the baseline.

**Comment by kpmokpmo** [comment]
@cheerss Thank you for quick reply. 
I am sorry for making you confused about the last question. The question essentially is would that be better if we replace the large kernel convolution(say 32 or 16) with multiple smaller convs just as we usually prefer two 3*3 convs to a 5*5 one.  According to "SegFormer: Simple and Efficient Design for Semantic Segmentation with Transformers" and "Convolution with even-sized kernels and symmetric padding", It might be better to use overlapped odd-size  kernel convolutions for embedding. Well, this is not a big issue afterall.

And one more thing, I didn't find a place to set the dilation rate or "I" for LSDA in the paper. Could you help me out? Many thanks.

**Comment by cheerss** [comment]
@kpmokpmo 

1. Yeah, maybe a series of 3x3 is better than a 32x32 for CrossFormer, or the case is opposite. I think it needs experiments for verifcation.

2. I = S / G, where S is height/width of feature maps. For models with input size 224x224, if G=7, the interval "I" for four stages are exactly [8, 4, 2, 1]. So, we set G rather than I for convenience (See [here](https://github.com/cheerss/CrossFormer/blob/main/models/crossformer.py#L237) for the code). For models for detection/segmentation, interval is [here](https://github.com/cheerss/CrossFormer/blob/main/models/crossformer_backbone.py#L198).

**Comment by kpmokpmo** [comment]
Get it.Thanks!
